version: "3.9"
services:
  remed-billin-api:
    container_name: remed-billin-api
    restart: always
    image: remed-billin-api
    environment:
      - REMED_DB=${REMED_DB}
      - BILL_IN_DB=${BILL_IN_DB}
      - LMDB_KEY=${LMDB_KEY}
    ports:
      - 7100:3000
    volumes:
      - ./volume:/app/volume
